title: Wendi Chen
logo: /assets/img/photo.png
description: Hi, I'm Wendi Chen and you can call me Andy.
 I'm now a sophomore from SJTU, majaring in Computer Science.
 I'll share what I'm working on these days on this page.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
