title: Wendi Chen
logo: /assets/img/photo2.png
description: Hi, I'm Wendi Chen and you can call me Andy.
 I'm now a sophomore from SJTU, majaring in Computer Science.
 I'll share the techniques or projects I worked on in recent days on this page.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
